// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Collected, CollectedTableId } from "./tables/Collected.sol";
import { Crafted, CraftedTableId } from "./tables/Crafted.sol";
import { Thirsty, ThirstyTableId } from "./tables/Thirsty.sol";
import { Hungry, HungryTableId } from "./tables/Hungry.sol";
import { Died, DiedTableId } from "./tables/Died.sol";
import { Monster, MonsterTableId } from "./tables/Monster.sol";
import { Resource, ResourceTableId } from "./tables/Resource.sol";
import { Item, ItemTableId } from "./tables/Item.sol";
import { MapConfig, MapConfigTableId } from "./tables/MapConfig.sol";
import { Obstruction, ObstructionTableId } from "./tables/Obstruction.sol";
import { Mineable, MineableTableId } from "./tables/Mineable.sol";
import { OwnedBy, OwnedByTableId } from "./tables/OwnedBy.sol";
import { Player, PlayerTableId } from "./tables/Player.sol";
import { Position, PositionTableId } from "./tables/Position.sol";
import { Movable, MovableTableId } from "./tables/Movable.sol";
import { Stats, StatsData, StatsTableId } from "./tables/Stats.sol";
import { Inventory, InventoryData, InventoryTableId } from "./tables/Inventory.sol";
