// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Resource, ResourceTableId } from "./tables/Resource.sol";
import { Item, ItemTableId } from "./tables/Item.sol";
import { MapConfig, MapConfigTableId } from "./tables/MapConfig.sol";
import { CollectionAttempt, CollectionAttemptTableId } from "./tables/CollectionAttempt.sol";
import { Obstruction, ObstructionTableId } from "./tables/Obstruction.sol";
import { Collectible, CollectibleTableId } from "./tables/Collectible.sol";
import { OwnedBy, OwnedByTableId } from "./tables/OwnedBy.sol";
import { Player, PlayerTableId } from "./tables/Player.sol";
import { Position, PositionTableId } from "./tables/Position.sol";
import { Movable, MovableTableId } from "./tables/Movable.sol";
