// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */
enum ResourceType {
  None,
  Wood,
  Stone,
  Water
}

enum ItemType {
  Axe,
  Pickaxe,
  Bucket
}

enum TerrainType {
  None,
  Tree,
  Rock,
  Sea,
  Wood,
  Stone,
  Water,
  Grass
}

enum MonsterType {
  None,
  Deer,
  Chicken
}
