// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */
enum ResourceType {
  Wood,
  Stone,
  Water
}

enum ItemType {
  Axe,
  Pickaxe,
  Bucket
}

enum TerrainType {
  None,
  Tree,
  Rock,
  Water
}
