// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IInventorySystem {
  function getAxe() external view returns (uint256);

  function getAxe(bytes32 player) external view returns (uint256);

  function getPickaxe() external view returns (uint256);

  function getPickaxe(bytes32 player) external view returns (uint256);

  function getBucket() external view returns (uint256);

  function getBucket(bytes32 player) external view returns (uint256);
}
