// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { TerrainType } from "./../Types.sol";

interface IMapSystem {
  function setTerrain(uint32 x, uint32 y, TerrainType terrainType) external;

  function removeTerrain(uint32 x, uint32 y) external;

  function spawn(uint32 x, uint32 y) external;

  function move(uint32 x, uint32 y) external;

  function mine(uint32 x, uint32 y) external;

  function craftAxe() external;

  function craftPickaxe() external;

  function craftBucket() external;

  function getAxe() external view returns (uint256);

  function getPickaxe() external view returns (uint256);

  function getBucket() external view returns (uint256);
}
