// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { TerrainType, Direction } from "./../Types.sol";

interface IMapSystem {
  function setTerrain(uint32 x, uint32 y, TerrainType terrainType) external;

  function removeTerrain(uint32 x, uint32 y) external;

  function spawn(uint32 x, uint32 y) external;

  function moveTo(uint32 x, uint32 y) external;

  function move(Direction direction) external;
}
