// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/interfaces/IBaseWorld.sol";

import { ICraftSystem } from "./ICraftSystem.sol";
import { IInventorySystem } from "./IInventorySystem.sol";
import { IMapSystem } from "./IMapSystem.sol";
import { IMineSystem } from "./IMineSystem.sol";
import { IStatsSystem } from "./IStatsSystem.sol";

/**
 * The IWorld interface includes all systems dynamically added to the World
 * during the deploy process.
 */
interface IWorld is IBaseWorld, ICraftSystem, IInventorySystem, IMapSystem, IMineSystem, IStatsSystem {

}
